# Grants super user permissions
sudo: required

# travis ci installs docker into travis container
services:
  - docker
# before tests are ran build docker image
before_install:
  - docker build -t dvontrec/fn-killers -f Dockerfile.dev .
script:
  # SHOULD ADD TESTS
  - docker run dvontrec/fn/killers npm run build
# Steps to deploy to github pages
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $github_token
  local_dir: build
  on:
    branch: master
