# Grants super user permissions
sudo: required

# travis ci installs docker into travis container
services:
  - docker
# before tests are ran build docker image
before_install:
  - docker build -t dvontrec/fn-killers -f Dockerfile.dev .
script:
  # SHOULD ADD TESTS
  - docker run dvontrec/fn-killers pwd
  - docker run dvontrec/fn-killers ls
# Steps before deploy:
defore_deploy:
  - docker run dvontrec/fn-killers -f npm run build
# Steps to deploy to github pages
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $github_token
  on:
    branch: master
# language: node_js
# node_js:
#   - 'stable'
# cache:
#   directories:
#     - node_modules
# script:
#   # - npm test
#   # - npm run test:coverage
#   - npm run build

# deploy:
#   provider: pages
#   skip_cleanup: true
#   github_token: $github_token
#   local_dir: build
#   on:
#     branch: master
